name: Publish to GitHub Packages

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << 'EOF'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and publish parent POM
        run: |
          cd parent
          mvn clean compile install deploy -DskipTests -Dsite-maven-plugin.skip=true || echo "Parent deploy failed (may already exist), continuing..."

      - name: Build and publish ddd package
        run: |
          cd ddd
          mvn clean compile install deploy -DskipTests -Dsite-maven-plugin.skip=true || echo "DDD deploy failed (may already exist), continuing..."

      - name: Build and publish test package
        run: |
          cd test
          mvn clean compile install deploy -DskipTests -Dsite-maven-plugin.skip=true || echo "Test deploy failed (may already exist), continuing..."

      - name: Build and publish util package
        run: |
          cd util
          mvn clean compile install deploy -DskipTests -Dsite-maven-plugin.skip=true || echo "Util deploy failed (may already exist), continuing..."

      - name: Build and publish checks package
        run: |
          cd checks
          mvn clean compile install deploy -DskipTests -Dsite-maven-plugin.skip=true || echo "Checks deploy failed (may already exist), continuing..."